### ISSUE TITLE
Release precompiled binary for NIF version `1.17` for x86 linux.

### ISSUE THREAD

**Issue by hansihe** [acalejos/exgboost#25]
Right now, as seen on the [release](https://github.com/acalejos/exgboost/releases/tag/v0.3.1) page, precompiled binaries are published for:

* Nif: 2.16, Target: aarch64-apple-darwin
* Nif: 2.16, Target: aarch64-linux-gnu
* Nif: 2.16, Target: riscv64-linux-gnu
* Nif: 2.16, Target: x86_64-linux-gnu
* Nif: 2.17, Target: aarch64-apple-darwin
* Nif: 2.17, Target: x86_64-apple-darwin

Would it be possible to publish binaries for

* Nif: 2.17, Target: x86_64-linux-gnu

as well?

**Comment by sitch** [comment]
bump -- having same problem

**Comment by acalejos** [comment]
@hansihe @sitch Hey, sorry I somehow missed this issue when it was opened. I am currently working on integrating some changes from the 2.0 release of XGBoost, but in the meantime I will push a new minor version with updating those packages.

**Comment by acalejos** [comment]
@hansihe @sitch Just pushed a new release with added artifacts and new Hex version with those checksums. Let me know if you're still having issues
