### ISSUE TITLE
Decision Tree introspection

### ISSUE THREAD

**Issue by nickgnd** [acalejos/exgboost#29]
Hey @acalejos 👋 
First of all, thanks for the great library, i'm playing with it and I found it really enjoyable. Thanks for all the work 🙇 

I have a question, I hope it is ok to open a issue on GH for that.
Is there any way to introspect the decision tree generated by the EXGBoost?

I don't have anything specific in mind, more general information about the tree, like the nodes and the conditions.
Ideally, it would be great to have the possibility to print the decision tree (or to export it in a printable format like the [dot](https://graphviz.org/doc/info/lang.html) one).

You likely already know that the python wrapper exposes an API to plot the tree https://xgboost.readthedocs.io/en/stable/python/python_api.html#module-xgboost.plotting

☝️ About that, I **naively** tried to serialize the EXGboost model and import it in Python using the `load_model` API in the `xgboost` library (https://xgboost.readthedocs.io/en/stable/python/python_api.html#xgboost.Booster.load_model) but it didn't work. I **naively** thought they format used for serialization was the same given that they are both shelling out the the C implementation (I think 😅 ).

Either i'm doing something wrong (most likely) or the format is not compatible with the one expected by the Python library.

Also, if I save it as JSON and try to open it in VSCode or other editor, it shows me this error message: "The file is not displayed in the text editor because it is either binary or uses an unsupported text encoding".

I tried with both `dump_model` and with `write_model`.

```elixir
model =
  EXGBoost.train(
      features,
      target_hot_encoded,
      obj: :binary_logistic,
      max_depth: 5
    )

EXGBoost.write_model(model, "/Users/nicolo.gnudi/dt1")

# OR 
# EXGBoost.dump_model(model) |> then(& File.write!("/Users/nicolo.gnudi/dt1.json", &1, [:binary]))
```

Then, if I inspect the codepoints I get this result:

```elixir
model
|> EXGBoost.dump_model()
|> String.codepoints()

[
  "{",
  "L",
  <<0>>,
  <<0>>,
  <<0>>,
  <<0>>,
  <<0>>,
  <<0>>,
  <<0>>,
  <<6>>,
  "C",
  "o",
  "n",
  "f",
  "i",
  "g",
  "{",
  "L",
  <<0>>,
  <<0>>,
  <<0>>,
  <<0>>,
  <<0>>,
  <<0>>,
  <<0>>,
  "\a",
  "l",
  "e",
  "a",
  "r",
  "n",
  "e",
  "r",
  "{",
  "L",
  <<0>>,
  <<0>>,
  <<0>>,
  <<0>>,
  <<0>>,
  <<0>>,
  <<0>>,
  "\r",
  "g",
  "e",
  "n",
  "e",
  "r",
  "i",
  "c",
  ...
]
```

The binary includes the null char `<<0>>` but also `<<6>>` and `<<22>>`. Do you know if this is expected? 

To conclude, if I try to import the serialized model in python I get the following error

```python
>>> import xgboost as xgb
>>> model = xgb.Booster()
>>> model.load_model("/Users/nicolo.gnudi/dt1.json")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nicolo.gnudi/.asdf/installs/python/3.10.12/lib/python3.10/site-packages/xgboost/core.py", line 2587, in load_model
    _check_call(_LIB.XGBoosterLoadModel(self.handle, c_str(fname)))
  File "/Users/nicolo.gnudi/.asdf/installs/python/3.10.12/lib/python3.10/site-packages/xgboost/core.py", line 281, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: [09:20:12] /Users/runner/work/xgboost/xgboost/src/common/json.cc:385: Expecting: """, got: "76 ", around character position: 1
    {L\0\0\0\0\0\0\0
    ^~~~~~~~~
Stack trace:
  [bt] (0) 1   libxgboost.dylib                    0x000000011ea3f355 dmlc::LogMessageFatal::~LogMessageFatal() + 117
  [bt] (1) 2   libxgboost.dylib                    0x000000011eaa9a56 xgboost::JsonReader::Error(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>) const + 1110
  [bt] (2) 3   libxgboost.dylib                    0x000000011eaa9f09 xgboost::JsonReader::Expect(signed char, signed char) + 265
  [bt] (3) 4   libxgboost.dylib                    0x000000011eaa1c7e xgboost::JsonReader::ParseObject() + 606
  [bt] (4) 5   libxgboost.dylib                    0x000000011eaa94af xgboost::JsonReader::Parse() + 415
  [bt] (5) 6   libxgboost.dylib                    0x000000011eaaa628 xgboost::Json::Load(xgboost::StringView, unsigned int) + 120
  [bt] (6) 7   libxgboost.dylib                    0x000000011ea66113 XGBoosterLoadModel + 435
  [bt] (7) 8   libffi.dylib                        0x00007ff822cee8c2 ffi_call_unix64 + 82
  [bt] (8) 9   ???                                 0x00007ff7b3c73650 0x0 + 140701849826896
```

Sorry for the super long message 🙈 

Please, let me know if there is anything that I can do, if you wanna I can share with you a livebook I'm working on.
Thanks again 🙇

**Comment by acalejos** [comment]
Hey @nickgnd, thanks for opening the issue! I agree that we need more support for interpretability for the models. We can use this issue to track that, but I think the first thing I would want to add is a visualization, likely using the [Kino](https://hexdocs.pm/kino/Kino.html) library. Regarding the particular use case you gave, there actually are currently ways to achieve what you're trying to achieve. When it comes to outputting the human-readable description of the booster, try using `Booster.get_dump/2` (https://hexdocs.pm/exgboost/EXGBoost.Booster.html#get_dump/2). That will produce something looking like:
```
0:[f0<4] yes=1,no=2,missing=2,gain=0.833333373,cover=3
	1:leaf=-0.150000006,cover=1
	2:[f0<7] yes=3,no=4,missing=4,gain=0.166666657,cover=2
		3:leaf=-0,cover=1
		4:leaf=0.150000006,cover=1
0:[f0<4] yes=1,no=2,missing=2,gain=0.602083325,cover=3
	1:leaf=-0.127500013,cover=1
	2:[f0<7] yes=3,no=4,missing=4,gain=0.120416671,cover=2
		3:leaf=-0,cover=1
		4:leaf=0.127500013,cover=1
0:[f0<4] yes=1,no=2,missing=2,gain=0.435005188,cover=3
	1:leaf=-0.108375005,cover=1
	2:[f0<7] yes=3,no=4,missing=4,gain=0.0870010406,cover=2
		3:leaf=-0,cover=1
		4:leaf=0.108374998,cover=1
0:[f0<4] yes=1,no=2,missing=2,gain=0.314291269,cover=3
	1:leaf=-0.092118755,cover=1
	2:[f0<7] yes=3,no=4,missing=4,gain=0.0628582537,cover=2
		3:leaf=-0,cover=1
		4:leaf=0.092118755,cover=1
0:[f0<4] yes=1,no=2,missing=2,gain=0.227075458,cover=3
	1:leaf=-0.0783009455,cover=1
	2:[f0<7] yes=3,no=4,missing=4,gain=0.045415096,cover=2
		3:leaf=-0,cover=1
		4:leaf=0.0783009455,cover=1
0:[f0<4] yes=1,no=2,missing=2,gain=0.164062008,cover=3
	1:leaf=-0.0665557981,cover=1
	2:[f0<7] yes=3,no=4,missing=4,gain=0.0328124017,cover=2
		3:leaf=-0,cover=1
		4:leaf=0.0665557981,cover=1
0:[f0<4] yes=1,no=2,missing=2,gain=0.118534818,cover=3
	1:leaf=-0.0565724298,cover=1
	2:[f0<7] yes=3,no=4,missing=4,gain=0.0237069689,cover=2
		3:leaf=-0,cover=1
		4:leaf=0.056572441,cover=1
0:[f0<7] yes=1,no=2,missing=2,gain=0.0856414065,cover=3
	1:[f0<4] yes=3,no=4,missing=4,gain=0.0171282776,cover=2
		3:leaf=-0.048086565,cover=1
		4:leaf=-0,cover=1
	2:leaf=0.0480865724,cover=1
0:[f0<7] yes=1,no=2,missing=2,gain=0.0618759319,cover=3
	1:[f0<4] yes=3,no=4,missing=4,gain=0.0123751815,cover=2
		3:leaf=-0.0408735797,cover=1
		4:leaf=-0,cover=1
	2:leaf=0.0408735946,cover=1
0:[f0<4] yes=1,no=2,missing=2,gain=0.0447053462,cover=3
	1:leaf=-0.0347425416,cover=1
	2:[f0<7] yes=3,no=4,missing=4,gain=0.00894107111,cover=2
		3:leaf=-0,cover=1
		4:leaf=0.0347425491,cover=1
```

And when trying to save to use in other API's you must use `EXGBoost.write_weights/2`, as that is the one that uses the `save_model` C API call under the hood. This should be made more clear in the documentation, something to the effect of "Use this call if you want to save to a universal format that can be loaded in other XGBoost APIs."  So something like the following should work:
```elixir
EXGBoost.write_weights(booster, "saved_booster")
```

Then you can use the Python you showed before:
```python
import xgboost as xgb
model = xgb.Booster()
model.load_model("/Users/nicolo.gnudi/saved_booster.json")
```

Let me know if that addresses the questions you had!

**Comment by nickgnd** [comment]
Hey @acalejos thank you so much for your quick reply, really helpful 🙇 

> We can use this issue to track that, but I think the first thing I would want to add is a visualization, likely using the [Kino](https://hexdocs.pm/kino/Kino.html) library.

It would be indeed great to have a Kino widget for that 🤩 Potentially, it should be possible to render the tree using mermaidjs, the only thing is that large decision trees would be hard to read, but this applies to every "simple" rendering tool that do not offer zooming/panning controls.

> When it comes to outputting the human-readable description of the booster, try using `Booster.get_dump/2`

Oh, I completely missed that, thanks! 🙈

For completeness, I share below my snippet to include the features name in each node (it was not so easy to find the expected format of the `fmap` file)

```elixir
# Write the `fmap` file, it should follow this format:
#
# ```
# 0 feature_name_1 q
# 1 feature_name_2 i
# 2 feature_name_3 i
# ```
#
# (q=quantitative feature, i=binary feature - https://stackoverflow.com/a/60186748)
# 
feature_names
|> Enum.with_index(fn element, index -> "#{index} #{element} q" end)
|> Enum.join("\n")
|> then(& File.write!("/Users/nicolo.gnudi/fmap.txt", &1))

EXGBoost.Booster.get_dump(model, fmap: "/Users/nicolo.gnudi/fmap.txt", format: :json)
```

> And when trying to save to use in other API's you must use EXGBoost.write_weights/2, as that is the one that uses the save_model C API call under the hood. 

It worked! Great, thank you 🙇 

Here the snippet I used to generate the Decision Tree graph (sharing for future readers).

```elixir
EXGBoost.write_weights(model, "/Users/nicolo.gnudi/dtw")
```

And then, plot the decision tree using the Python `xgboost` library:

```python
❯ python3
>>> import xgboost as xgb
>>> model = xgb.Booster()
>>> model.load_model("/Users/nicolo.gnudi/dtw.json")
>>>
>>> xgb.to_graphviz(model)
<graphviz.sources.Source object at 0x106542350>
>>> g = xgb.to_graphviz(model, fmap="/Users/nicolo.gnudi/fmap.txt")
>>> g.render(filename="/Users/nicolo.gnudi/dtg")
'/Users/nicolo.gnudi/dtg.pdf'
```

Again, thank you for the great library and the all the help!
Feel free to close the issue.
Cheers ✌️
