### ISSUE TITLE
Problems installing exgboost in livebook

### ISSUE THREAD

**Issue by hiramegl** [acalejos/exgboost#39]
Hi,

I've been using livebook for a while and I'm trying to run the Iris classification example  at:
https://hexdocs.pm/exgboost/0.5.0/iris_classification.html

I write this in the setup cell (just like in the example):

Mix.install([
  {:exgboost, "\~> 0.4"},
  {:nx, "\~> 0.5"},
  {:scidata, "\~> 0.1"},
  {:scholar, "\~> 0.1"}
])

Unfortunately, I get this warning:

23:25:17.977 [warning] The on_load function for module Elixir.EXGBoost.NIF returned:
{:error,
 {:load_failed,
  ~c"Failed to load NIF library: 'dlopen(/Users/hiram/Library/Caches/mix/installs/elixir-1.15.7-erts-14.1.1/102c8b1d69b78ce545ebc04ce45ad196/_build/dev/lib/exgboost/priv/libexgboost.so, 0x0002): Library not loaded: /opt/homebrew/opt/libomp/lib/libomp.dylib\n  Referenced from: <7834DF63-8443-3E17-8C61-5AD8FC9345BC> /Users/hiram/Library/Caches/mix/installs/elixir-1.15.7-erts-14.1.1/102c8b1d69b78ce545ebc04ce45ad196/_build/dev/lib/exgboost/priv/lib/libxgboost.dylib\n  Reason: tried: '/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file)'"}}

23:25:17.977 [notice] Application exgboost exited: exited in: EXGBoost.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function EXGBoost.NIF.set_global_config/1 is undefined (module EXGBoost.NIF is not available)
            (exgboost 0.5.0) EXGBoost.NIF.set_global_config("{\"verbosity\":0,\"use_rmm\":false}")
            (exgboost 0.5.0) lib/exgboost.ex:184: EXGBoost.set_config/1
            (exgboost 0.5.0) lib/exgboost/application.ex:6: EXGBoost.Application.start/2
            (kernel 9.1) application_master.erl:293: :application_master.start_it_old/4

I've checked and the "libexgboost.so" file actually is found in "exgboost/priv".

When i run the cell for training: "... EXGBoost.train( ..." I get the error:

** (UndefinedFunctionError) function EXGBoost.NIF.get_binary_address/1 is undefined (module EXGBoost.NIF is not available)
    (exgboost 0.5.0) EXGBoost.NIF.get_binary_address(<<102, 102, 246, 64, 0, 0, 64, 64, 51, 51, 195, 64, 51, 51, 19, 64, 102, 102, 150, 64, 205, 204, 76, 64, 205, 204, 204, 63, 205, 204, 76, 62, 205, 204, 204, 64, 205, 204, 44, 64, 154, 153, 169, 64, 51, 51, 243, 63, 205, 204, ...>>)
    (exgboost 0.5.0) lib/exgboost/array_interface.ex:129: EXGBoost.ArrayInterface.from_tensor/1
    (exgboost 0.5.0) lib/exgboost/dmatrix.ex:309: EXGBoost.DMatrix.from_tensor/2
    (exgboost 0.5.0) lib/exgboost.ex:249: EXGBoost.train/3
    #cell:fhe4zu7q6payxerwyhtao572majr44yt:2: (file)

BTW, version "\~>0.4" is used in the example, but the documentation is for version "0.5.0", is it supposed to be like that?
I've also tried using {:exgboost, "\~> 0.5"} but got the same error.

Do I need to install something outside livebook, in the host computer?
I'm running livebook in a macbook pro with Sonoma, maybe that is the problem.

Thanks for your help in advance!

Best regards,

/Hiram Galicia

**Comment by acalejos** [comment]
For MacOS you need to intall `libomp` which you can do with `brew install libomp`. Depending on how your livebook is set up it could be easier to compile and start an iex session outside of live book and connect it it separately rather than using a standalone livebook instance. 

Try installing `libomp` and let me know if that resolves it for you

**Comment by acalejos** [comment]
Also, regarding the livebook specifying the old version, that's an error. It just got missed in the update.

**Comment by hiramegl** [comment]
Hi Andrés,

Yes, it worked like a charm after running "brew install libomp". I just reopened the notebook in livebook and worked.
I saw this in the requirements but misunderstood it. Thought it was only if I'd be contributing to the library.

By the way, do you know if Apple Metal will be supported in the future? I see CUDA is in the roadmap.

Many thanks again for the help and great job with the library.

Best regards,

/Hiram Galicia

**Comment by acalejos** [comment]
Glad it worked! I'll go ahead and close the issue. 

I do think there are plans to add a metal backend. I believe it's actively being developed. 

In the meantime, you can use https://github.com/acalejos/mockingjay to compile your trained `EXGBoost.Booster`'s to `Nx` code and then leverage all of the benefits from that ecosystem. 

You can see an example of how to do that at https://www.thestackcanary.com/serving-spam-detection-with-xgboost-and-elixir/

**Comment by hiramscb** [comment]
Thanks Andrés!

That sounds like good news with metal backend!
Absolutely, I'll take a look at the post.
Thanks for your great job!

Best regards,

/Hiram Galicia
